repos:
  - repo: https://github.com/psf/black
    rev: 21.4b0
    hooks:
      - id: black
        exclude: ^pdm/_vendor
  - repo: https://github.com/PyCQA/flake8
    rev: 3.9.1
    hooks:
      - id: flake8

  - repo: https://github.com/pycqa/isort
    rev: 5.8.0
    hooks:
      - id: isort

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.812
    hooks:
      - id: mypy
        args:
          - --follow-imports=skip
        files: | # incremental 'fully-typed' list
          (?x)^(
              pdm/exceptions.py|
              pdm/formats/.*\.py|
              pdm/models/auth.py|
              pdm/models/caches.py|
              pdm/models/python.py|
              pdm/models/setup.py|
              pdm/models/specifiers.py|
              pdm/models/versions.py|
              pdm/termui.py|
              pdm/utils.py|
          )$
