[tool.pdm]
python_requires = ">=3.7"

[tool.pdm.dependencies]
appdirs = "*"
click = "*"
distlib = "*"
parver = "<1.0.0,>=0.2.1"
pip = "<20.0.0,>=19.3.1"
pip_shims = "*"
pythonfinder = "*"
tomlkit = "*"

[tool.pdm.dev-dependencies]
pytest = "*"
pytest-cov = "*"
pytest-mock = "*"

[tool.isort]
line_length = 88
multi_line_output = 3
include_trailing_comma = true
use_parentheses = true
force_grid_wrap = 0
atomic = true
not_skip = "__init__.py"
skip_glob = ["*/setup.py"]
filter_files = true
known_first_party = "pdm"
known_third_party = "pip_shims"

[tool.black]
line-length = 88
