[tool.pdm]
python_requires = ">=3.7"

[tool.pdm.dependencies]
appdirs = "*"
click = "*"
distlib = "*"
pip = "<20.0.0,>=19.3.1"
pip_shims = "*"
pythonfinder = "*"
tomlkit = "*"
halo = "<1.0.0,>=0.0.28"

[tool.pdm.dev-dependencies]
pytest = "*"
pytest-cov = "*"
pytest-mock = "*"

[tool.coverage.run]
branch = true

[tool.coverage.report]
# Regexes for lines to exclude from consideration
exclude_lines = [
    "pragma: no cover",
    # Don't complain about missing debug-only code:
    "def __repr__",
    "if self.debug",
    # Don't complain if tests don't hit defensive assertion code:
    "raise AssertionError",
    "raise NotImplementedError",
    # Don't complain if non-runnable code isn't run:
    "if __name__ == .__main__.:"
]
omit = ["pdm/__main__.py"]
ignore_errors = true

[tool.isort]
line_length = 88
multi_line_output = 3
include_trailing_comma = true
use_parentheses = true
force_grid_wrap = 0
atomic = true
not_skip = "__init__.py"
skip_glob = ["*/setup.py"]
filter_files = true
known_first_party = "pdm"
known_third_party = "pip_shims"

[tool.black]
line-length = 88
