[tool.pdm]
python_requires = ">=3.6"

[tool.pdm.dependencies]
requests = "~=2.19.0"
django = ">=2.0, <3.0"

[tool.pdm.dev-dependencies]
pytest = "*"

[tool.isort]
line_length = 88
multi_line_output = 3
include_trailing_comma = true
use_parentheses = true
not_skip = "__init__.py"
skip_glob = ["*/setup.py"]
filter_files = true
known_first_party = "pdm"
known_third_party = "pip_shims"

[tool.black]
line-length = 88
