site_name: PDM - Python Development Master

repo_url: https://github.com/frostming/pdm

theme:
  name: material

nav:
  - index.md
  - dependency.md
  - project.md
  - pyproject.md
  - plugin.md
  - contributing.md
  - changelog.md

markdown_extensions:
  - pymdownx.highlight:
      linenums: true
  - pymdownx.superfences
  - admonition
  - tables
  - toc:
      permalink: "#"
  - markdown_include.include:
      base_path: docs

copyright: Copyright &copy; 2019-2020 <a href="https://frostming.com">Frost Ming</a>
