site_name: PDM - Python Development Master

repo_url: https://github.com/pdm-project/pdm

theme:
  name: material
  palette:
    primary: deep purple
    accent: teal
  font:
    text: Open Sans
    code: Fira Code
  logo: assets/logo.png
  favicon: assets/logo.png
  custom_dir: overrides

nav:
  - Home: index.md
  - Usage:
      - Manage Dependencies: usage/dependency.md
      - Manage Project: usage/project.md
      - Advanced Usage: usage/advanced.md
  - Writing pyproject.toml:
      - pyproject/pep621.md
      - pyproject/tool-pdm.md
  - Configuration: configuration.md
  - Plugins:
      - plugin.md
  - Development:
      - contributing.md
      - changelog.md

markdown_extensions:
  - pymdownx.highlight:
      linenums: true
  - pymdownx.superfences
  - admonition
  - tables
  - toc:
      permalink: "#"
  - markdown_include.include:
      base_path: docs

copyright: Copyright &copy; 2019-2021 <a href="https://frostming.com">Frost Ming</a>

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/pdm-project/pdm
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/pdm_project
    - icon: fontawesome/brands/discord
      link: https://discord.gg/CEUwAmYm
