site_name: PDM - Python Development Master

repo_url: https://github.com/frostming/pdm

theme:
  name: material
  palette:
    primary: deep purple
    accent: teal
  font:
    text: Open Sans
    code: Fira Code
  logo: assets/logo.png
  favicon: assets/logo.png

nav:
  - index.md
  - dependency.md
  - project.md
  - pyproject.md
  - advanced.md
  - plugin.md
  - contributing.md
  - changelog.md

markdown_extensions:
  - pymdownx.highlight:
      linenums: true
  - pymdownx.superfences
  - admonition
  - tables
  - toc:
      permalink: "#"
  - markdown_include.include:
      base_path: docs

copyright: Copyright &copy; 2019-2021 <a href="https://frostming.com">Frost Ming</a>
