name: Run Benchmark

on:
  workflow_dispatch:

jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: 3.9
      - name: Install PDM
        run: |
          python -m pip install rich
          python install-pdm.py --version head
          echo "$HOME/.local/bin" >> $GITHUB_PATH
      - name: Bootstrap poetry
        run: |
          curl -sL https://install.python-poetry.org | python - -y
      - name: Install Pipenv
        run: python -m pip install -U pipenv
      - name: Run Benchmark script
        run: python3 tasks/benchmarks/main.py
