name: Documentation

on:
  push:
    branches:
      - main
    paths:
      - "*.md"
      - docs/**
      - "!pdm/**"

jobs:
  build-doc:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
          architecture: "x64"
      - name: Build pages
        run: |
          pip install -U pip wheel
          pip install mkdocs mkdocs-material markdown-include
          cd docs && mkdocs build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/site
