name: Release

on:
  push:
    tags:
      - "*"

jobs:
  release-pypi:
    name: release-pypi
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: 3.8
          architecture: "x64"
      - name: Get Changelog
        id: get-changelog
        run: |
          echo "::set-output name=CHANGELOG_CONTENT::$(awk '/-{3,}/{flag=1;next}/Release/{if (flag==1)exit}flag' CHANGELOG.md)"
      - name: Install Current PDM
        run: |
          pip install -U pip
          pip install .
      - name: Build artifacts
        run: |
          pdm build -v
      - name: Test Build
        run: |
          python3 -m venv fresh_env
          . fresh_env/bin/activate
          pip install dist/*.whl
          fresh_env/bin/pdm --help
      - name: Upload to Pypi
        run: |
          pip install twine
          twine upload --username __token__ --password ${{ secrets.PYPI_TOKEN }} dist/*
      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: v${{ github.ref }}
          body: ${{ steps.get-changelog.outputs.CHANGELOG_CONTENT }}
          draft: false
          prerelease: false
